baseurl: /jekyll_demo
gems: [jekyll-paginator]

paginate_path: 'page:num'
paginate: 1
category: category

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
encoding: utf-8


