baseurl:     /jekyll_demo
gems:        [jekyll-paginator]
encoding:    UTF-8
paginate_path: 'page:num'
paginate: 5

host:        0.0.0.0
port:        4000
baseurl:     /jekyll_demo
url:         http://localhost:4000



